trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**
      - azure-pipelines.yml

pr:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**
      - azure-pipelines.yml

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: '1.16.0'
  terraformWorkingDirectory: 'terraform'

steps:
  - checkout: self

  - script: |
      TEMP_DIR=$(mktemp -d)

      curl -fsSLo "$TEMP_DIR/terraform.zip" \
        https://releases.hashicorp.com/terraform/$(terraformVersion)/terraform_$(terraformVersion)_linux_amd64.zip

      unzip -o "$TEMP_DIR/terraform.zip" -d "$TEMP_DIR"

      sudo install "$TEMP_DIR/terraform" /usr/local/bin/terraform

      terraform version
    displayName: 'Install Terraform'

  - script: terraform fmt -check -recursive
    workingDirectory: $(terraformWorkingDirectory)
    displayName: 'Terraform Format Check'

  - task: AzureCLI@2
    displayName: 'Terraform Init, Validate, and Plan'
    inputs:
      azureSubscription: 'sc-terraform-azure-iac-lab'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      workingDirectory: '$(terraformWorkingDirectory)'
      inlineScript: |
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)

        terraform init
        terraform validate
        terraform plan -input=false -no-color